### PR TITLE
Close the files after reading

### PR DESCRIPTION
**Pull request by Ark-kun**
This fixes the following warning:

>site-packages/strip_hints/token_list.py:176: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp8xo7fe2z'>
>  self.read_from_file(kwargs["filename"])

Changed `get_xxx_reader` to `get_xxx_stream`.

### CODE REVIEW

**Comment by abarker** [comment]
How are you running the program to get that warning?  I've run it on Ubuntu with Python 2.7, 3.6, and 3.7 and I don't get any warning.

The tests I'm running are located in the directory `test` and are encapsulated in the Bash script `run_tests.bash`.  Just execute that shell script from that directory to run them.

Even though Python eventually closes files before exiting, at least with a normal exit, it's always a good idea to explicitly close them.  In that sense your code change is cleaner.  Unfortunately, it is failing the second round of tests with `NameError: name 'get_string_reader' is not defined` because not all instances of `get_string_reader` are updated to the new name.

**Comment by Ark-kun** [comment]
>How are you running the program to get that warning? I've run it on Ubuntu with Python 2.7, 3.6, and 3.7 and I don't get any warning.

I see those warnings when running Python 3 (3.5, 3.6, 3.7) unittests on Travis: https://travis-ci.com/kubeflow/pipelines/jobs/289562999#L770

>Unfortunately, it is failing the second round of tests

Sorry. I was just using GitHub to edit the files and made a mistake. The tests succeed now.

**Comment by abarker** [comment]
FYI, the new version (0.1.8) has now been pushed to PyPI.

**Comment by Ark-kun** [comment]
> FYI, the new version (0.1.8) has now been pushed to PyPI.

Thank you!

**Pull request merged**
